### ISSUE TITLE
Cannot install due to conflict

### ISSUE THREAD

**Issue by mariusl** [m-schaeffler/node-red-my-nodes#2]
I am running NR under homeassistant and the only way to install is by using the panel manager. There is another "counter" node listed under the functions section of the NR node selections. It is "node-red-contrib-counter".
I have no way of removing the installed node as it seems to be a built in function. 
Is there a way that I can overcome this issue at all?

**Comment by Kilill** [comment]
Same issue here....

**Comment by m-schaeffler** [comment]
As homeassistant is no node-red project, but just integrates node red, it cannot be detected automatically by the tests.
A rename is not possible without breaking existing projects.

**Comment by mariusl** [comment]
I don't think homeassistant is responsible for the node. It is a node-red built in node. Has nothing to do with HA.
