### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by PiteousHonking** [m-schaeffler/node-red-my-nodes#6]
After installing nodes are not available and the following is displayed in the Manage Palettes Menu
![image](https://github.com/m-schaeffler/node-red-my-nodes/assets/36885071/88ae45ee-69cf-4671-9697-b8c46ae709ae)

Node-red v3.0.2
 Armbian 23.02.6 Jammy with Linux 5.15.43

**Comment by m-schaeffler** [comment]
Can you pleased add the Version of nodejs you are using?

**Comment by PiteousHonking** [comment]
Hmm, v12.22.9

let me see if an update resolves it

**Comment by PiteousHonking** [comment]
Update to v18.17.1 resolves it, thanks.

**Comment by m-schaeffler** [comment]
I updated the package description so that nodejs 14 ist required.
