### ISSUE TITLE
node-red-logic conflicting with node-red-contrib-counter

### ISSUE THREAD

**Issue by hp32i6g0x** [m-schaeffler/node-red-my-nodes#8]
I've been having trouble getting it to work. I think it might be conflicting with the default counter package that's installed in the Home Assistant Node-RED instance. I've tried uninstalling the counter package, but I'm not sure how to do it permanently. Could you please provide some guidance on how to get your palette working on my system? Thanks in advance for your help!

https://github.com/m-schaeffler/node-red-my-nodes/assets/106186039/f3101c56-88bd-4b4b-b8cf-0a92beaeff59

**Comment by tomaswilhelmsson** [comment]
Having same problem, tried uninstalling the homeassistant counter from docker shell but it just appears again after restart of node red.

**Comment by kneefabio** [comment]
The same problem

**Comment by m-schaeffler** [comment]
HOmeAssistant is not supported by me.
THis are nodes for use in nodered.
